# Plasma Agent Default Configuration
# This file contains default settings for the Plasma Agent system

agent:
  name: "PlasmaAgent"
  description: "Plasma Engine Agent orchestration service"
  version: "0.1.0"

# LLM Configuration
llm:
  # Supported providers: "openai", "anthropic"
  provider: "openai"

  # Model configurations by provider
  models:
    openai:
      default: "gpt-4"
      options:
        - "gpt-4"
        - "gpt-4-1106-preview"
        - "gpt-4-turbo"
        - "gpt-3.5-turbo"
        - "gpt-3.5-turbo-1106"
    anthropic:
      default: "claude-3-sonnet-20240229"
      options:
        - "claude-3-opus-20240229"
        - "claude-3-sonnet-20240229"
        - "claude-3-haiku-20240307"

  # Generation parameters
  temperature: 0.7
  max_tokens: null  # null means use model default
  timeout: 60
  max_retries: 3

# Memory Configuration
memory:
  database_path: "agent_memory.db"
  enable_conversation_history: true
  max_conversation_length: 100
  cleanup_interval: 3600  # seconds

# Tool Configuration
tools:
  enabled: true

  # File system tools
  file_system:
    enabled: true
    allowed_extensions:
      - ".txt"
      - ".md"
      - ".json"
      - ".yaml"
      - ".yml"
      - ".py"
      - ".js"
      - ".ts"
    max_file_size: 10485760  # 10MB in bytes

  # Web search tools
  web_search:
    enabled: true
    engine: "duckduckgo"
    max_results: 5
    timeout: 10

  # Shell command tools
  shell:
    enabled: true
    allowed_commands:
      - "ls"
      - "pwd"
      - "echo"
      - "cat"
      - "head"
      - "tail"
      - "grep"
      - "find"
      - "wc"
      - "date"
      - "which"
      - "whoami"
    timeout: 30

# Task Execution
tasks:
  max_concurrent: 5
  default_timeout: 300  # 5 minutes
  max_iterations: 10  # Maximum tool call iterations
  auto_retry: true
  retry_count: 3
  retry_delay: 1.0  # seconds

# Logging Configuration
logging:
  level: "INFO"
  format: "{time} | {level} | {name}:{function}:{line} - {message}"
  rotation: "1 day"
  retention: "1 week"
  compression: "gz"

# System Prompts
prompts:
  system: |
    You are PlasmaAgent, an advanced AI assistant designed to help users with various tasks.

    You have access to tools that allow you to:
    - Read and write files
    - Search the web for information
    - Execute safe shell commands
    - Manage tasks and conversations

    Always be helpful, accurate, and safe in your responses. When using tools, explain what you're doing and why.
    If you encounter errors, try alternative approaches when possible.

    Keep your responses clear and concise while being thorough when needed.

  task_prefix: |
    Task Context:
    - You are working on the following task
    - Use available tools to complete the task effectively
    - Provide clear updates on your progress

  error_handling: |
    When encountering errors:
    1. Analyze the error message
    2. Try alternative approaches if available
    3. Provide clear feedback about what went wrong
    4. Suggest next steps to the user

# Security Configuration
security:
  enable_sandbox: true
  max_tool_execution_time: 60
  restrict_file_access: true
  allowed_domains: []  # empty means all domains allowed for web search
  blocked_domains:
    - "localhost"
    - "127.0.0.1"
    - "0.0.0.0"

# Performance Configuration
performance:
  enable_caching: true
  cache_ttl: 3600  # 1 hour
  concurrent_tool_calls: 3
  streaming_enabled: true
  compression_enabled: true

# Development Configuration
development:
  debug_mode: false
  enable_mock_responses: false
  log_api_calls: false
  save_raw_responses: false
  test_mode: false